### ISSUE TITLE
BUG: bcrypt.js

### ISSUE THREAD

**Issue by md-asharaf** [hiteshchoudhary/apihub#100]
### Describe the bug

does not export default 

### Screenshots

![Screenshot 2024-03-12 211501](https://github.com/hiteshchoudhary/apihub/assets/113321839/d1692e70-7d39-4303-94e5-ef4881001023)

### OS

Windows

### OS Version

11

### Client

chrome

**Comment by md-asharaf** [comment]
please fix this

**Comment by zaheershaikh936** [comment]
Hi there,

I'm interested in contributing to this project. I've been following apihub for a while now and I'm a big fan of open source project.

I'm familiar with javascript and typescript and I'd be happy to help out in any way I can. can you assign this issue to me please?

**Comment by wajeshubham** [comment]
@md-asharaf can you check if you are getting the same issue with NodeJs LTS version 20?

**Comment by wajeshubham** [comment]
Closing as stale
