### ISSUE TITLE
FEATURE: Order Return Request Controller Should be there in this repo

### ISSUE THREAD

**Issue by joydeep808** [hiteshchoudhary/apihub#104]
### Describe the Feature

Return Request  Controller not there 
and also in orderModels currentStatus is should be there 
currentStatusEnum = ["PENDING" , "SHIPED" , "DELEVERED" , "CENCELLED"]

**Comment by wajeshubham** [comment]
Please elaborate on the issue a bit @joydeep808

**Comment by joydeep808** [comment]
We want to add order return request because return Route should be there in ecom backend
 and also in order Model a status field should be there 
because from the status we know the current status of the order 
for example 
when a new order is created than the status is by default PENDING 
after shiped the product status updated to SHIPED if order Cencelled than show the user that the order is cencelled 

i think in this repo cancellation route also not there

**Comment by joydeep808** [comment]
i am interested to contribute and  add this controllers

**Comment by wajeshubham** [comment]
Explain us what endpoint you will be adding and whats the logic of the whole flow of returning an order from customer point of view as well as admin point of view. Also, there is already a `status` field in order model which shows current status of the order.

**Comment by joydeep808** [comment]
/createNewReturn -----> in this route when a order status is delevered and also from the delivery date i will count if the delivery date is already passed 7 days 
than user not able to return this product and if not user can return this product 
and when a return request is created than the initial status will be PENDING and after the admin review in this concern admin can reject or accept the return after return request is completed 
the refund will be issued for the user 
the motive to add this route to provide the user to return delivered product 
/getAllPendingReturnRequest
/updateReturnRequestStatus admin can REJECT and APPROAVE And DIRECTLY APPROAVE IN CASE MISSING OR NON RETURNABLE PRODUCT

**Comment by joydeep808** [comment]
and we also want to integrate the curiour services in this repo to get the tracking info and updated information
like when a delivery person delivered the product than automatically updates status in our db

**Comment by joydeep808** [comment]
should i start working on this?

**Comment by wajeshubham** [comment]
@joydeep808 after reviewing this feature we think for now introducing the return product feature might be little bit redundant as there's no shipping service integration, but we are considering this feature for the next major version where we might introduce some 3rd party shipping services integration in the FreeAPI but for now introducing the return product feature might be a bit redundant. We appreciate your contribution though!

Best regards,
FreeAPI team
