### ISSUE TITLE
FRONTEND: Online platform to sell old things

### ISSUE THREAD

**Issue by mirajhad** [hiteshchoudhary/apihub#105]
Frontend App Title
E-Shopify

Overview
E-Shopify is a modern online shopping platform built using React.js and Tailwind CSS, offering a sleek and intuitive user interface for seamless shopping experiences.

Detailed Features
User Authentication:

Users can easily register accounts or log in securely to access personalized features and track their orders.
Product Discovery:

Comprehensive search and filter options enable users to discover products effortlessly based on categories, brands, or specifications.
Shopping Cart Management:

Intuitive cart functionality allows users to add, remove, or update items, ensuring a smooth and convenient shopping experience.
Secure Checkout Process:

Multiple payment gateways ensure secure transactions, providing users with various options to complete their purchases with confidence.
Order Tracking:

Users can track their orders in real-time, receiving updates on order status and delivery information for enhanced transparency.
Tech Stack Used
Frontend Framework: React.js
Styling: Tailwind CSS
Built For Platform
E-Shopify is optimized to run on various platforms, providing flexibility and scalability. Hosting options include services like Vercel, Netlify, or traditional web hosting providers.

E-Shopify offers a seamless online shopping experience, combining the power of React.js for dynamic user interfaces and Tailwind CSS for elegant and responsive designs. With its user-friendly features and robust functionality, E-Shopify ensures a delightful shopping journey for every customer.

**Comment by wajeshubham** [comment]
@mirajhad we already have an issue opened for the same application with almost the same tech stack in issue #85 

We are checking on the activity of that issue and we will let you know if you can proceed with this app.

Thank you

**Comment by mirajhad** [comment]
Thanks @wajeshubham for update.

**Comment by jwala-anirudh** [comment]
Hi @mirajhad,

Can you share any skeleton design / outline of all the website pages that you plan to build?

**Comment by arnb-smnta** [comment]
@mirajhad  I have also raised same type of issue #85 is closed by maintainer wanna collab together and make the frontend of e-commerce web-app

**Comment by arnb-smnta** [comment]
@mirajhad How can i contact you are you on discord arnub_sama this is my discord user name send a connect request we can discuss about the project there

**Comment by mirajhad** [comment]
sure @arnb-smnta

**Comment by jwala-anirudh** [comment]
Apologies, I have reopened. Based on your earlier discussion I understood that you both will be working together and come up with a plan of action.

If that is the case can close this issue & you can raise one more in upcoming days.

**Comment by mirajhad** [comment]
sure @jwala-anirudh
