### ISSUE TITLE
BUG: Address Not Found after deleting it in orders.

### ISSUE THREAD

**Issue by Sarthak-ONS** [hiteshchoudhary/apihub#106]
### Describe the bug

Hi, I just found out a use case. 
Suppose a user place an order with a specific address (represented by an address object's Mongoose ID). Later, if the user deletes that address and then fetches the order again, the order should still display the original address details associated with that address ID at the time the order was placed, rather than showing the updated address details if the address was later modified.

### To Reproduce

Just create an order, and delete address that was used for that order, and fetch the same order again by ID

### Expected behavior

The very first details with which order was placed must be given in the response.
Thanks!

### OS

All

### Client

Postman

**Comment by vaibhav-jadhav** [comment]
Hi @Sarthak-ONS 

I can think of two solutions here:

Soft Deletion:
Do not delete the addresses permanently from the database. Instead, maintain a state of the address like active/inactive or have a boolean flag, is_deleted, which can be false initially. When the user deletes that address, make it true. Ensure that deleted addresses are not displayed for selection as the shipping address. However, soft deletion only works in the case of address deletion, not in address updating.

Order-Address Association:
When a user places an order, store the address details directly with the order as order_address. This ensures that the order always retains the original address details, even if the address is later modified or deleted. Additionally, store the reference to the original address object (e.g., address ID) along with the order for future reference. order_address will include the following data:

OrderID
AddressID
Other address information such as landmark, street, city, pincode, etc.
I have not seen the codebase yet as this is my first day at APIHub. I will go through the code and see what can be done if my above solution doesn’t fit the need.

Thanks!

**Comment by Sarthak-ONS** [comment]
> Hi @Sarthak-ONS
> 
> I can think of two solutions here:
> 
> Soft Deletion: Do not delete the addresses permanently from the database. Instead, maintain a state of the address like active/inactive or have a boolean flag, is_deleted, which can be false initially. When the user deletes that address, make it true. Ensure that deleted addresses are not displayed for selection as the shipping address. However, soft deletion only works in the case of address deletion, not in address updating.
> 
> Order-Address Association: When a user places an order, store the address details directly with the order as order_address. This ensures that the order always retains the original address details, even if the address is later modified or deleted. Additionally, store the reference to the original address object (e.g., address ID) along with the order for future reference. order_address will include the following data:
> 
> OrderID AddressID Other address information such as landmark, street, city, pincode, etc. I have not seen the codebase yet as this is my first day at APIHub. I will go through the code and see what can be done if my above solution doesn’t fit the need.
> 
> Thanks!

hi @vaibhav-jadhav , yes I was thinking same, but user can delete address, we must directly add complete address  obj instead of addressId

**Comment by vaibhav-jadhav** [comment]
yes that what I mentioned stored address id is  for future reference only.
we need to copy all address details into new table.
here is example.

```
Order:{
id: 1,
products:[], 
userId: 'user123'
}
```

```
Address:{
id: 2
landmark: 'opposite XYZ bank',
city: 'Pune',
pin: 123456
}
```

```
OrderAddress:{
order_id: 1,
address_id: 2,
landmark: 'opposite XYZ bank',
city: 'Pune',
pin: 123456
}
```

**Comment by vaibhav-jadhav** [comment]
here.
doesn't matter if original address is updated or deleted.
we still have details with order.

**Comment by wajeshubham** [comment]
@vaibhav-jadhav @Sarthak-ONS Thank you for pointing out the issue. I think soft deletion is the better and scalable option as it does not introduce duplication and also takes care of data integrity by using the same document which we show to user and associate with the order collection. 

This solution requires fewer changes to the address model and application logic since it involves **marking** addresses as deleted rather than actually removing them from the database. This also ensures that, order addresses stay synchronized with any updates to actual addresses.

Let us know if anyone is interested to contribute to resolve this issue or shall we start working on the issue internally.

Thank you!

Best regards,
FreeAPI team

**Comment by Sarthak-ONS** [comment]
Hi @wajeshubham, consider a scenario where an order was placed using Address ID "123" with Object A. Later, the user updates the same address "123" with Object B. Although the Address ID remains the same, the details have been updated. This situation may raise legal concerns and should be addressed. I will resolve this issue and submit a pull request. Thank you.

**Comment by wajeshubham** [comment]
@Sarthak-ONS Yup agree! but what if user actually entered wrong address in the first place? we have two things here, either keep soft deletion or add edit functionality in orders address field so that after placing if user wants to change the address he/she can do that. As this project will not be used by the users directly we can implement either of two but I would suggest, build the one which is less lengthy and also introduces some concepts of backend like soft deletion.

**Comment by Youngemmy5956** [comment]
@Sarthak-ONS i created a pull request on this, so u can check it out.

**Comment by Youngemmy5956** [comment]
> @vaibhav-jadhav @Sarthak-ONS Thank you for pointing out the issue. I think soft deletion is the better and scalable option as it does not introduce duplication and also takes care of data integrity by using the same document which we show to user and associate with the order collection.
> 
> This solution requires fewer changes to the address model and application logic since it involves **marking** addresses as deleted rather than actually removing them from the database. This also ensures that, order addresses stay synchronized with any updates to actual addresses.
> 
> Let us know if anyone is interested to contribute to resolve this issue or shall we start working on the issue internally.
> 
> Thank you!
> 
> Best regards, FreeAPI team

@wajeshubham can i work on this issue?
