### ISSUE TITLE
Hey Sir their seems to b an issue

### ISSUE THREAD

**Issue by Coderx011** [hiteshchoudhary/apihub#111]
![image](https://github.com/hiteshchoudhary/apihub/assets/134941383/4d40f00a-71b1-4143-998b-1ab127ccdfb2)

{MongoDB connection error:  Error: queryTxt ETIMEOUT cluster0.fphzhgd.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:275:17) {
  errno: undefined,
  code: 'ETIMEOUT',
  syscall: 'queryTxt',
  hostname: 'cluster0.fphzhgd.mongodb.net'
}
[nodemon] app crashed - waiting for file changes before starting...

i countinously getting this error and app creashed

**Comment by wajeshubham** [comment]
Please refer to this issue: #97

**Comment by wajeshubham** [comment]
Please check this issue for the possible solution: #97
