### ISSUE TITLE
FEATURE: Add single vendor e-commerce admin panel backend api

### ISSUE THREAD

**Issue by vivekmodi23** [hiteshchoudhary/apihub#117]
### Describe the Feature

Features list of single vendor e-commerce admin panel application

- Dashboard
- Sub admin manager
- Users list
- Order management
- Delivery boy management
- Coupon management
- Earning management
- Stock management
- Notification manager
- Report manager
- Static content manager
- Email template manager
- Global settings

### 1. Dashboard:
- **View Dashboard**: Admins can access a centralized dashboard displaying key metrics and insights about the e-commerce platform's performance, including sales revenue, order volume, and customer engagement metrics.

### 2. Sub Admin Manager:
- **Create Sub Admin**: Admins can create new sub-administrator accounts with specific roles and permissions tailored to their responsibilities.
- **Manage Sub Admins**: Admins can view, edit, and deactivate existing sub-administrator accounts, adjusting their permissions and access levels as needed.

### 3. Users List:
- **View User List**: Admins can access a list of registered users on the platform, including their contact information, order history, and account status.
- **Search and Filter Users**: Admins can search for specific users and apply filters to narrow down the user list based on criteria such as registration date or geographic location.

### 4. Order Management:
- **View Orders**: Admins can view a list of all orders placed by customers, including order details, customer information, and current status.
- **Update Order Status**: Admins can update the status of orders as they progress through the fulfillment process, such as marking orders as confirmed, shipped, or delivered.
- **Manage Returns and Refunds**: Admins can handle customer requests for returns and refunds, processing refunds and updating inventory accordingly.

### 5. Delivery Boy Management:
- **Assign Delivery Boys**: Admins can assign delivery personnel to specific orders for fulfillment, tracking the status of each delivery and managing delivery schedules.
- **Monitor Delivery Performance**: Admins can track the performance of delivery personnel, including metrics such as delivery times and customer satisfaction ratings.
- **Manage Delivery Zones**: Admins can define and manage delivery zones, specifying geographic areas where orders can be delivered and assigning delivery personnel accordingly.

### 6. Coupon Management:
- **Create Coupons**: Admins can create discount coupons and promotional codes for use by customers during checkout, specifying details such as discount amount, expiration date, and usage limits.
- **Track Coupon Usage**: Admins can monitor the usage of coupons, tracking metrics such as redemption rates and revenue generated through coupon campaigns.
- **Manage Coupon Campaigns**: Admins can organize and manage multiple coupon campaigns, scheduling promotions and targeting specific customer segments.

### 7. Earning Management:
- **View Earnings**: Admins can view detailed reports of earnings generated through sales, commissions, and other revenue streams.
- **Track Affiliate Earnings**: Admins can track earnings generated by affiliate marketers and other partners, managing payouts and commissions.
- **Generate Earning Reports**: Admins can generate reports summarizing earnings over specific time periods, facilitating financial analysis and decision-making.

### 8. Stock Management:
- **Manage Inventory**: Admins can track and manage product inventory levels, adjusting stock quantities and receiving alerts for low stock levels.
- **Handle Stock Replenishment**: Admins can initiate stock replenishment processes, such as placing orders with suppliers or transferring inventory between warehouses.
- **Monitor Stock Movement**: Admins can track stock movements and adjustments, including sales, returns, and damaged goods.

### 9. Notification Manager:
- **Send Notifications**: Admins can send notifications to customers, delivery personnel, and other stakeholders via email, SMS, or push notifications.
- **Manage Notification Templates**: Admins can create and customize notification templates for different types of messages, such as order confirmations, shipping updates, and promotional announcements.
- **Schedule Automated Notifications**: Admins can schedule automated notifications to be sent at specific times or triggered by predefined events, such as order fulfillment or product restocks.

### 10. Report Manager:
- **Generate Reports**: Admins can generate various reports summarizing key performance metrics and business insights, such as sales reports, inventory reports, and customer analytics.
- **Customize Report Parameters**: Admins can customize report parameters and filters to generate tailored reports based on specific criteria and time periods.
- **Export Reports**: Admins can export reports in different formats (e.g., PDF, CSV) for further analysis or sharing with stakeholders.

### 11. Static Content Manager:
- **Manage Static Pages**: Admins can create and edit static pages such as About Us, FAQ, and Terms of Service, managing the content and layout of each page.
- **Publish Content Updates**: Admins can publish updates to static pages, ensuring that the information displayed to customers is accurate and up-to-date.
- **Control Page Visibility**: Admins can control the visibility of static pages, determining which pages are accessible to customers and which are hidden or restricted.

### 12. Email Template Manager:
- **Customize Email Templates**: Admins can customize email templates for automated communications sent to customers, such as order confirmations, password resets, and promotional emails.
- **Preview Email Templates**: Admins can preview email templates to ensure that they are formatted correctly and contain the desired content before sending.
- **Manage Template Versions**: Admins can manage multiple versions of email templates, enabling A/B testing and iterative improvements to email communications.

### 13. Global Settings:
- **Configure Platform Settings**: Admins can configure global settings and preferences for the e-commerce platform, such as currency, language, and tax settings.
- **Manage Payment and Shipping Options**: Admins can configure payment gateways, shipping carriers, and other integrations, customizing settings to meet business requirements.
- **Control Platform Policies**: Admins can define and enforce platform policies, such as return policies, privacy policies, and terms of service, ensuring compliance with legal and regulatory requirements.

### Suggested Tools

- Node JS
- MongoDB
- Express JS
- Api Testing [Postman]
- Api formating [Swgger]

**Comment by wajeshubham** [comment]
@vivekmodi23 after going through the feature list, I think similar module already exist in core FreeAPI apps module which has complete admin panel management as well as other e-com features including payment gateway integration. How is it different from the existing e-com module.

**Comment by vivekmodi23** [comment]
@wajeshubham, I am closing this issue as I checked that we have rich admin panel for the same. I have one more idea which i have share on other issues as feature. Sharing the link here.
https://github.com/hiteshchoudhary/apihub/issues/127
Looking forward to work with team.
Happy Coding.
