### ISSUE TITLE
FEATURE:Would like to add a edit message controller in Chat-app Backend and would like to add the delete message option in the official  frontend of the chat app 

### ISSUE THREAD

**Issue by arnb-smnta** [hiteshchoudhary/apihub#118]
### Describe the Feature

Would like to add a edit message endpoint in the backend of the chat-app and also would like to add the delete message feature in the frontend in the official frontend of the chat-app .
@wajeshubham 

### Use Case

User can edit the message they have sent in group chat and one to one chat only messages not attachments

### Additional Information

Would like to add the delete message feature in the frontend for user to be able to delete the message will modify the frontend code that is written in react-tailwind that is present in the repo.

**Comment by wajeshubham** [comment]
Edit message is not that relevant for this version of the chat message but we will consider this in future. But you can start working on the delete message functionality frontend changes for the existing frontend chat app. No need to create issue for that you can directly open a PR for that. Closing this issue for now. Thank you!
