### ISSUE TITLE
ENHANCEMENT: Public api performance Improvement  

### ISSUE THREAD

**Issue by Mitesh0807** [hiteshchoudhary/apihub#119]
### Describe the enhancement

In order to pointout the getPublics method (book,cat,dog,meal,randomjoke,randomproduct,stock), we perform data filtering through search key processing. Upon discovering included keys in the query parameters, we proceed with the entire filterout process and eliminate the keys. Alternatively, we can obtain the paginated payload first, which can greatly enhance performance, and then remove the key. 

### Additional Information

suggested solution but there can be more cleaner solution just pointing out this we can process lot less data for removing keys 
```javascript
let booksArray = query
    ? structuredClone(booksJson).filter((book) => {
        return (
          book.searchInfo?.textSnippet.toLowerCase().includes(query) ||
          book.volumeInfo.title?.includes(query) ||
          book.volumeInfo.subtitle?.includes(query)
        );
      })
    : structuredClone(booksJson);

//if (inc && inc[0]?.trim()) {
// booksArray = filterObjectKeys(inc, booksArray);
//}
const paginatedResponse = getPaginatedPayload(booksArray, page, limit)
  const updatedBooks = inc
    ? filterObjectKeys(inc, paginatedBooks.data)
    : paginatedBooks.data;
  return res.status(200).json(
    new ApiResponse(
      200,
      {
        ...paginatedBooks,
        data: updatedBooks,
      },
      "Books fetched successfully"
    )
  );
});
```

### Additional Context or Information

Hopefully i submitted issue right way if not please let me know and if provided info is right , i can work on this enhancement

**Comment by Mitesh0807** [comment]
@wajeshubham sure man!

**Comment by Mitesh0807** [comment]
@wajeshubham created pull request for this pls check ! 😊

**Comment by wajeshubham** [comment]
PR: #125
