### ISSUE TITLE
FEATURE: Add logout feature in the web app of chat-app in the frontend /make the UI of the web-app responsive for smaller screen sizes

### ISSUE THREAD

**Issue by arnb-smnta** [hiteshchoudhary/apihub#122]
### Describe the Feature

The chat-app does not have a log out feature in the web version will like to add it in the frontend ,the backend api is present will add the option for user to log out of the app and will redirect to login page .

Chat-app is not responsive for smaller screens will like to make it responsive for smaller screen sizes for mobile browsers or Tab Browsers

### Use Case

User will be able to log out and can log in with his diffrent ids

Will be able to use the app in different devices with better UI compatibility.

**Comment by wajeshubham** [comment]
@arnb-smnta You can implement logout feature but we won't encourage making example application which are built by FreeAPI team mobile responsive as of now as those applications are not hosted anywhere

**Comment by PsammystPrime** [comment]
> @arnb-smnta You can implement logout feature but we won't encourage making example application which are built by FreeAPI team mobile responsive as of now as those applications are not hosted anywhere

I agree. Couldn't find a link to the said chat-app.

**Comment by arnb-smnta** [comment]
@wajeshubham I will just implement the logout features
