### ISSUE TITLE
FRONTEND: Ecommerce Web APP using React-Vite-Tailwind

### ISSUE THREAD

**Issue by arnb-smnta** [hiteshchoudhary/apihub#124]
### Frontend App Title

E-SHOP

### Overview

I would like to build an ecommerce web application using React-Js

<h1>FrameWorks</h1>
<ul>
<li>ReactJS (TypeScript)</li>
<li>Axios -For fetching Api's</li>
<li>Redux -For stateManagement</li>
<li>Tailwind Css for styling </li>
<li>React Icons for icons</li>
</ul>

### Detailed Features

<h1>Features</h1>
<ul>
<li>Users can create , Login,update  their accounts</li>
<li>Search and filter functionality for the users</li>
<li>Users can browse  different products by search text or category products list their products for sell or delete their products </li>
<li>User can add /remove products in cart or from cart</li>
<li>User can see coupons available in the checkout page and apply them on checkout </li>
<li>User can have diffrent address and edit the adresss</Li>
<li>Will also integrate the razor and paypal payment provider api on checkout</li>
<li>user can also check for  order status if payment is succesfull will show delivered if unsuccesfull will show payment failed reorder option will be there</li>
<li>Will also add a User Page for user to redirect to his order history and his listed products currently </li>
</ul>

As #85 is invalid can i work on it I can do it with react i dont have good understanding of next-js currently @wajeshubham @jwala-anirudh 

### Tech Stack Used

Reactjs,redux,tailwind

### Built For Platform

web (responsive for mobile browsers only)

### Project Path

RootFolder/examples/apps/ecommerce/web/react-vite-tailwind

**Comment by jwala-anirudh** [comment]
Hi @arnb-smnta,

After reading the features you listed, I would ask you to go through [the FreeAPI docs](https://api.freeapi.app/#/%F0%9F%9B%92%20Ecommerce) once again & update us back if you can cover all the available endpoints in your application.

**Comment by arnb-smnta** [comment]
Hi @jwala-anirudh I have gone through  the api docs I can cover all the  ecommerce api endpoints given in the docs ,I was also thinking of covering most of the user api's apart from the common ones like register and login I was thinking of email verification options and change-password ,forgot password ,reset password  and user avatar update also .

**Comment by arnb-smnta** [comment]
@jwala-anirudh any update on this

**Comment by jwala-anirudh** [comment]
You can liaise with @mirajhad (issue #105) as I don't want duplication of same project with different names, please share a skeleton design of all pages that you plan to build. Along with that, also mention page-wise APIs that will be utilising. In this way, both of us are clear on where we are headed towards

**Comment by wajeshubham** [comment]
@arnb-smnta Closing for time being. Once you guys are done with planning please let us know. Thanks!
