### ISSUE TITLE
Refresh token should be array

### ISSUE THREAD

**Issue by Mecsan** [hiteshchoudhary/apihub#131]
### Describe the bug

In the user model (src/models/apps/auth/user.models.js) 
the refresh token is string that means and on every login we are overriding the refresh token, that means if a use has logged in into 2 devices then in the user model the refresh token will be of last logged in device, so when the access token of 1st device expired and user sent a request for generating new access token with refresh token, it will not match with the refresh token stored in the user model as it has been override by the 2nd device login. 
Similarly when a use log out we are removing the refresh token means, if a  user is logged into multiple devices and in one of the device he logged out then he can't re generate the access token in any of the other devices as well because the refresh token is removed from the user model

**Comment by Youngemmy5956** [comment]
Working on this already

**Comment by Youngemmy5956** [comment]
@hiteshchoudhary @sangamesh1439 Can i work on this??
