### ISSUE TITLE
Mongodb connection in local host 

### ISSUE THREAD

**Issue by asif-iqbal-ba** [hiteshchoudhary/apihub#132]
When I used mongodb in local .env variable 
MONGODB_URI=mongodb://mongodb:27017
did not work then i changed it as given below
MONGODB_URI=mongodb://127.0.0.1:27017 
and it worked for me.

---------
Aother issue is that sometimes below code to connect mongodb in local do not work

let connectionInstance = await mongoose.connect(`${process.env.MONGODB_URI}/${DB_NAME}` );

We get error about topology then we should add a parameter in it like below
let connectionInstance = await mongoose.connect(`${process.env.MONGODB_URI}/${DB_NAME}`,
{ useNewUrlParser: true, useUnifiedTopology: true } );

**Comment by SohamM2003** [comment]
use `mongodb://localhost:27017` or `mongodb://127.0.0.1:27017`

**Comment by wajeshubham** [comment]
Use `MONGODB_URI=mongodb://mongodb:27017` when you are using docker and use `MONGODB_URI=mongodb://localhost:27017` when using local mongo cluster.
