### ISSUE TITLE
Whenever I call the register users API, I receive the response correctly, but the email is not being retrieved correctly

### ISSUE THREAD

**Issue by Mohammed81423** [hiteshchoudhary/apihub#139]

**Comment by Sarthak-ONS** [comment]
Hi @Mohammed81423 , Can u please share more info on this issue?

**Comment by Mohammed81423** [comment]
Yesterday and today i tried when i entered this four things  username, mail
, password , Admin rule   getting 200 response correctly but email isnt
getting on my personal mail  please check and once you try

**Comment by Mohammed81423** [comment]
No not yet.

**Comment by Mohammed81423** [comment]
Hitesh sir post any video  regarding env and authentication please send me
video

**Comment by arnb-smnta** [comment]
you need to clone the project make a .env file in it copy paste the contents of env sample in .env and enter your personal mail gen credentials to get a verify email after installing the project
