### ISSUE TITLE
Responsive issue

### ISSUE THREAD

**Issue by Sachin-kumar-jha** [hiteshchoudhary/apihub#141]
Responsivenes issue when drop-down open

**Comment by arnb-smnta** [comment]
can u elaborate which drop down and what issue

**Comment by Sachin-kumar-jha** [comment]
Good afternoon sir,
Sorry for late reply for some issues.

When I click freeapi.app,
redirect to your web page .
I click cooked docs and click kitchen-sink-api.
Where responsive issue in phone-version this drop-down:
GET:/kitchen-sink/redirect/to Redirect url.

If this helpful for you then it would be my pleasure.
