### ISSUE TITLE
BUG: refreshToken not properly cleared in database upon user logout

### ISSUE THREAD

**Issue by KadlagAkash** [hiteshchoudhary/apihub#147]
### Describe the bug

- When users send a `POST` request to the `api/v1/user/logout` endpoint, the intention is to clear the `refreshToken` stored in the database. 

- However, a bug has been identified in the provided code where setting `refreshToken` to undefined does not update the refreshToken value in the database as expected.

### To Reproduce

1. Send a `POST` request to the `api/v1/user/logout` endpoint.

2. Check the database to verify if the `refreshToken` value is successfully cleared.

### Expected behavior

After sending a `POST` request to the `api/v1/user/logout` endpoint, the `refreshToken` value in the database should be cleared.

### Screenshots

![image](https://github.com/hiteshchoudhary/apihub/assets/100425384/20bbd831-48bc-405a-99fa-e91a869b07e5)

![image](https://github.com/hiteshchoudhary/apihub/assets/100425384/eeac0986-f314-4cb1-b77c-09a336bf4e32)

### OS

MacOs

### OS Version

14.4.1

### Client

Postman

### Additional context or Information

To fix this issue, instead of setting refreshToken to undefined, the code should set it to an empty string (''). This ensures that the refreshToken value is properly updated in the database. [Here](https://github.com/hiteshchoudhary/apihub/blob/5f2dec6320665b1b600daa1de8acd8e446b17c24/src/controllers/apps/auth/user.controllers.js#L166) 

```js
await User.findByIdAndUpdate(
    req.user._id,
    {
      $set: {
        refreshToken: '',
      },
    },
    { new: true }
);
`````

**Comment by wajeshubham** [comment]
@KadlagAkash Thank you for the issue. Let us know if you can work on this one.

**Comment by KadlagAkash** [comment]
@wajeshubham Yes, I can work on this. I'll submit a pull request soon.
