### ISSUE TITLE
FEATURE: UI Enhancement Proposal: Transforming User Interface for Better Engagement

### ISSUE THREAD

**Issue by askadityapandey** [hiteshchoudhary/apihub#161]
### Describe the Feature

The current look of the HERO page doesn't match the aesthetic. I think we can improve it, currently the WEBSITE using basic NEXT JS template. I'll love to work with you guys and contribute to improve the UI. I've right set of skills which is required to make this website page better and also updating links too!
Can I proceed to work on it?  

### Use Case

The improved UI will make this project more serious looking.

**Comment by wajeshubham** [comment]
@askadityapandey Thank you for showing interest to improve FreeAPI website UI. This repo is not housing the website code but the actual FreeAPI functionality code base. To contribute in FreeAPI website please visit this repo: https://github.com/hiteshchoudhary/freeApiAppWeb
