### ISSUE TITLE
BUG: layout affecting in free api docs while  on clicking on the schema view of data.json (on clicking cookie)

### ISSUE THREAD

**Issue by aman-kumar162** [hiteshchoudhary/apihub#162]
### Describe the bug

**Issue Summary**: Layout disruption when clicking on the schema view of data.json (specifically on "cookie") in the free API docs.
**Steps to Reproduce**: 1. Open the free API documentation.
                                        2. Click on the schema view of data.json.
                                        3.   Click on the "cookie" section.
**Expected Behavior**: The schema view should display without affecting the overall layout of the page. 
**Actual Behavior**: Clicking on the "cookie" section causes elements to overlap, making the documentation difficult to read. **Severity**: High (prevents effective use of the documentation).
**Attachments**:![Screenshot 2024-05-19 091520](https://github.com/hiteshchoudhary/apihub/assets/116007359/2e2c7e8d-03d2-4924-a1d8-fe467983a3ba) 
**Notes**: This appears to be a CSS conflict when rendering the schema view.

**Comment by wajeshubham** [comment]
@aman-kumar162 Thank you for addressing the issue. However, the docs are getting generated through swagger and UI is auto controlled by swagger UI. The issue doesn't seem to break the core functionality of the FreeAPI and hence we can afford to ignore this style discrepancy.

Thank you
