### ISSUE TITLE
BUG: Error in Assert keyword parsing in node version 22.2.0

### ISSUE THREAD

**Issue by arnb-smnta** [hiteshchoudhary/apihub#168]
### Describe the bug

<img src="https://res.cloudinary.com/dxfdxwvlm/image/upload/v1717750445/Screenshot_from_2024-06-07_14-22-51_yz1z4m.png"/>

<h1>Assert keyword is throwing error with higher node js versions such as 22.2.0 but working fine with 20.0.0 </h1>

<h2>It should work with node version higher than 16 but I don't know why is it not working</h2>
### To Reproduce

<h2>Update your nvm version to 22.2.0 using nvm use 22.2.0 and run the server using 'npm run start' it will throw the above listed error</h2>

### Expected behavior

<h3>It should run fine without any problems</h3>

### OS

Linux

**Comment by wajeshubham** [comment]
Currently we recommend node version to be <=v20 and v22 is not an LTS version as of now.
