### ISSUE TITLE
BUG: Brocken link in issues/new page

### ISSUE THREAD

**Issue by ruru-m07** [hiteshchoudhary/apihub#172]
![image](https://github.com/hiteshchoudhary/apihub/assets/142723369/aa19f4e6-2089-455c-af0c-440e74924791)
![image](https://github.com/hiteshchoudhary/apihub/assets/142723369/f349e293-2c02-4739-b440-9afa18b1845a)

https://github.com/hiteshchoudhary/apihub/blob/435b1647a804ff1ed4fd4f2d4bd0d14ab68e89ce/.github/ISSUE_TEMPLATE/config.yml#L4

**Comment by wajeshubham** [comment]
Thanks for pointing out @ruru-m07
