### ISSUE TITLE
feat(chat-app): missing endpoint

### ISSUE THREAD

**Issue by ruru-m07** [hiteshchoudhary/apihub#173]
### There is no such an endpoint to get "One on one chat" 

![image](https://github.com/hiteshchoudhary/apihub/assets/142723369/63c2d186-14d8-434f-b3b0-33ed40a98c40)

with GET:`/chat-app/chats/group/{chatId}` can't get "One on one chat" it trow ApiResponse 404 because of:

![image](https://github.com/hiteshchoudhary/apihub/assets/142723369/5240b432-2fc4-4513-977c-59704d412753)

### Use Case

I am currently working on a chat app with nextJS and I follow the URL structure like:- `http://localhost:3000/c/66699203a8c87ed1133e5bf5`

and then on that page, I tried to find the chat details but the problem was not fixed by just adding a new endpoint that needed a better structure because we don't know if chat ID `66699203a8c87ed1133e5bf5` is a group chat or one on one chat. 

### Suggested Tools

my suggest is:-

```diff
 const groupChat = await Chat.aggregate([
   {
     $match: {
       _id: new mongoose.Types.ObjectId(chatId),
-       isGroupChat: true,
     },
   },
   ...chatCommonAggregation(),
]);
```

**Comment by arnb-smnta** [comment]
Get one one chat is not required in the API's because if you go through the frontend app you can see we are retrieving the user chats using get chats/user and it returns us chatIds with this on CLick on the chat Id we can get all the messages of one to one chat and group chat from backend using messages/chat-id ,   and the end point you have provided '/chat-app/chats/group/{chatId}' u can see it just provides details of group such as group name and group members we don't need that for one on one chat because it just has user name shown in it , one on chat endpoint that you suggested might be required in the future if we add details to use to view may be his pro pic or status or phone number etc ,but collaborators I think will not accept such proposals they want to keep it basic and functionality rich not full fledged chat -app like , I had proposed many such features they didn't accept

**Comment by ruru-m07** [comment]
@arnb-smnta, I think there's a misunderstanding. Please refer to the "Use Case" section of the issue I provided earlier.

Let's say we have this chat object:

![image](https://github.com/hiteshchoudhary/apihub/assets/142723369/ed10fd65-4fdb-4ac5-a185-06d3c570fa81)

This is a "One on one chat". I want to retrieve only the data of that specific object, not all chats.

You suggested using "/chat-app/chats/users", but that returns all chats, which I don't need.

If you believe it's possible to retrieve only the data for a specific one-on-one chat, please demonstrate how. Create a one-on-one chat and try to retrieve only that single object (excluding "/chat-app/chats/users").

**Comment by arnb-smnta** [comment]
You think you don't get me there is nothing to retrieve from one on one chat except messages

**Comment by arnb-smnta** [comment]
Even if you want one on one chat you need chat I'd for that

**Comment by ruru-m07** [comment]
> Even if you want one on one chat you need chat I'd for that

@arnb-smnta I already have chatID in params

**Comment by arnb-smnta** [comment]
What do you want to retrieve from one to one chat?

**Comment by ruru-m07** [comment]
> What do you want to retrieve from one to one chat?

@arnb-smnta i need an endpoint where I can get the single chat data like this but I only have chatID

```json
{
  "_id": {
    "$oid": "66699203a8c87ed1133e5bf5"
  },
  "name": "One on one chat",
  "isGroupChat": false,
  "participants": [
    {
      "$oid": "66642d5b7b568aae3f53043c"
    },
    {
      "$oid": "66629ede998062c1ceeeb954"
    }
  ],
  "admin": {
    "$oid": "66642d5b7b568aae3f53043c"
  },
  "createdAt": {
    "$date": "2024-06-12T12:18:11.116Z"
  },
  "updatedAt": {
    "$date": "2024-06-12T13:51:06.164Z"
  },
  "__v": 0,
  "lastMessage": {
    "$oid": "6669a7ca1a7f88acb82d7cf7"
  }
}
```
I am currently working on a chat app with nextJS and I follow the URL structure like:- 
 http://localhost:3000/c/66699203a8c87ed1133e5bf5

 and then on that page, I tried to find the chat details but the problem was not fixed by just adding a new endpoint that needed a better structure because we don't know if chat ID 66699203a8c87ed1133e5bf5 is a group chat or one on one chat.

if you struggle with this issue than feel fee to leave

**Comment by arnb-smnta** [comment]
Yeah I get ur point there is not end point for that has to be created

**Comment by arnb-smnta** [comment]
If you require that for your project you have to create it

**Comment by ruru-m07** [comment]
> If you require that for your project you have to create it

hmm let's see

**Comment by wajeshubham** [comment]
There is no need for this API to built as the detail of one on one chat is detail of the other participant's details in which you can utilize get user profile api.
