### ISSUE TITLE
FEATURE: Adding Internationalization (i18n)

### ISSUE THREAD

**Issue by ram-prasad23** [hiteshchoudhary/apihub#174]
### Describe the Feature

# Feature Request: Internationalization (i18n) Support

## Summary

Add support for Internationalization (i18n) to the backend to handle requests in multiple languages. When a request comes with a query parameter `lg=ta` (Tamil) or `lg=en` (English), the response should be in the requested language. If the query parameter is not present or the requested language is not supported, the response should default to English.

## Description

The goal is to implement i18n support in the Node.js backend to enhance user experience by providing responses in their preferred language. This feature will detect the language from the query parameter `lg` in the request URL and send the response in the corresponding language. If the requested language is not supported or the `lg` parameter is not provided, the response will default to English.

## Implementation Steps

1. **Add Dependencies**:
   - Use a library like `i18n` or `i18next` to handle translation files and middleware setup.
   - Ensure to update `package.json` with the new dependencies.

2. **Set Up Middleware**:
   - Create middleware to detect the `lg` parameter from the request URL.
   - Load the appropriate language file based on the `lg` parameter or default to English.

3. **Create Translation Files**:
   - Set up translation JSON files for supported languages (e.g., `en.json` for English, `ta.json` for Tamil).
   - Place translation files in a directory structure that the i18n library can easily access.

4. **Update Responses**:
   - Modify existing endpoints to use the i18n library to return translated responses.
   - Ensure that dynamic content in responses also gets translated.

### Use Case

- In frontend we support internationalization. So it will be usefull if we implement it and get the response in the language the requested.

### Response (Tamil)

```json
{
  "status":200,
  "message": "வணக்கம், இது உங்கள் கோரிக்கைக்கு பதிலாக இருக்கும்."
}

### Additional Information

_No response_

### Suggested Tools

i18n

### Additional Context or Information

_No response_

**Comment by wajeshubham** [comment]
@ram-prasad23 Thank you for the great suggestion. However, we are not really considering internationalization at this early stage of freeapi but we will surely consider it in near future.
