### ISSUE TITLE
Email Verification Error: Token is Invalid or Expired

### ISSUE THREAD

**Issue by agareaditya-8055** [hiteshchoudhary/apihub#176]
**Description**
I encountered an issue with the email verification process. The token sent in the verification email does not match the token stored in the database.

**Steps to Reproduce**
1. Register a new user using the API endpoint `http://localhost:8080/api/v1/users/register`.
2. Check the response and the MongoDB database to verify the stored token.
3. Try to verify email using API endpoint `http://localhost:8080/api/v1/users/verify-email/{verificationToken}`
4. Observe the error message.

**Expected Outcome**
Email is verified

**Actual Outcome**
The server responds with a "Token is invalid or expired" error.

**Error Message**
```json
{
  "statusCode": 489,
  "data": null,
  "success": false,
  "errors": [],
  "message": "Token is invalid or expired",
  "stack": "Error: Token is invalid or expired\n    at file:///path/to/user.controllers.js:212:11\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
}

**Comment by surajcan30t** [comment]
## Problem while hitting the endpoint.
While trying to hit the endpoint `http://localhost:8080/api/v1/users/register` just getting a blank page

## Screenshot
![Screenshot (316)](https://github.com/hiteshchoudhary/apihub/assets/111273335/71c265c7-d031-457b-a40a-62bcd2d95707)

**Comment by agareaditya-8055** [comment]
Thank you. Now its working.

**Comment by wajeshubham** [comment]
Correct flow: https://github.com/hiteshchoudhary/apihub/pull/177#issuecomment-2174215519
