### ISSUE TITLE
Issue in users/forgot-password

### ISSUE THREAD

**Issue by shayaan-1** [hiteshchoudhary/apihub#190]
I was using users/forgot-password to send reset email to my email.
It is not sending mail to the email address provided.

Your response will be valuable.

**Comment by Sarthak-ONS** [comment]
Hi, @shayaan-1, Have you added proper email creds in env file?

**Comment by wajeshubham** [comment]
@shayaan-1 we are using the `mailtrap` library to send emails, if you want to enable email sending, kindly populate following env vars with appropriate credentials in the .env file.

```.env
# ################ ENV VARS TO SEND MAILS THROUGH MAILTRAP START #################
MAILTRAP_SMTP_HOST=__mailtrap_smtp_host__
MAILTRAP_SMTP_PORT=__mailtrap_smtp_port__
MAILTRAP_SMTP_USER=__mailtrap_smtp_user_id__
MAILTRAP_SMTP_PASS=__mailtrap_smtp_user_password__
# ################ ENV VARS TO SEND MAILS THROUGH MAILTRAP END #################
```

Thank you!
