### ISSUE TITLE
Ecom Api Issue

### ISSUE THREAD

**Issue by malikkhumza** [hiteshchoudhary/apihub#191]
Hello, I have been trying to work on ecom get products by id api and i almost tried for 2 3 hours but could not get any valid response.
The thought that there might be any porbem with API never crossed my mind as it was provided by the great Sir Hitesh. But i guess i was wrong this time. Then after so many tries i checked the api in the freeapi docs and found out that there is no response(404). I checked one or two more APIs and found one more broken API. 
So i am here to inform you that you should have your team fix it incase anyone else might be facing the same issue. BTW i learned a lot while integrating this broken API. I dont know if the problem is on your side or mine but i think its on your side( I hope so.)
Thanks in advance. Love from Lahore,PK❤.

**Comment by adityaRawat14** [comment]
hi can I  try to fix this issue ?
