### ISSUE TITLE
CORS policy issue in todos PATCH API

### ISSUE THREAD

**Issue by HimansuWebCoder** [hiteshchoudhary/apihub#196]
When updated my todo list with patch method this showed me. Solve the Access-Control-Allow-Methods  issue.
Why this issue came. please solve this. 

Access to fetch at 'https://api.freeapi.app/api/v1/todos/66dad45997bedfaf8fdcc000' from origin 'http://localhost:8080' has been blocked by CORS policy: Method patch is not allowed by Access-Control-Allow-Methods in preflight response.
![Screenshot from 2024-09-06 15-52-13](https://github.com/user-attachments/assets/0e636228-11e6-4120-a89c-83d979cd5c33)

![Screenshot from 2024-09-06 15-53-17](https://github.com/user-attachments/assets/591835c3-a1d9-47ec-b04c-ce2d0ad29e65)

**Comment by Sarthak-ONS** [comment]
Hi @HimansuWebCoder, Can you please share your cors policy, and your frontend headers

**Comment by HimansuWebCoder** [comment]
Sure, I set my headers and this is correct application/json I set, Isn't it. But this issue arising again and again. 


This is the issue:
Access to fetch at 'https://66dae132f47a05d55be64eb1.mockapi.io/api/v1/todos/10' from origin 'null' has been blocked by CORS policy: Method patch is not allowed by Access-Control-Allow-Methods in preflight response.

**Comment by wajeshubham** [comment]
What's the `CORS_ORIGIN` env var value in your .env?
