### ISSUE TITLE
Why no typescript?

### ISSUE THREAD

**Issue by bhumit070** [hiteshchoudhary/apihub#20]
I have a question
Why this project is built with javascript as more projects are adopting typescript why are we not using the same here.
Just for the question.

**Comment by hiteshchoudhary** [comment]
Such questions can be asked on discord or live stream. Opening an issue for this increase the maintenance work.

**Comment by bhumit070** [comment]
> Such questions can be asked on discord or live stream. Opening an issue for this increase the maintenance work.

Created this issue here so that if someone does not use Discord or something else app then they can have a look here as well.
Apologies for the inconvenience.
