### ISSUE TITLE
FEATURE: <Update Coding Hero Site>

### ISSUE THREAD

**Issue by Code-With-Abhishek-Kumar** [hiteshchoudhary/apihub#259]
### Describe the Feature

![Screenshot from 2024-10-26 21-51-49](https://github.com/user-attachments/assets/e852ae5b-dfa3-46ad-ba18-9161fd9b3a87)

We want   New Features for Event Management in https://www.chaicode.com/ch/events

### 1. Event Application for Admins

**Objective**: Enable admins to easily submit and manage events.

**Benefits**:
- **Streamlined Process**: Simplifies event proposal submissions.
- **Clear Guidelines**: Ensures all necessary information is included.
- **Increased Engagement**: Encourages more participation from admins.

**Implementation Steps**:
- **Application Form**: 
  - Fields include:
    - Event Title
    - Date and Time
    - Location (or virtual link)
    - Description
    - Target Audience
    - Contact Information
- **Review System**: Allows event submissions to be approved or rejected by moderators.
- **Confirmation Notifications**: Automatic notifications upon approval or requests for further details.

### 2. Chat Section for Mentor Communication

**Objective**: Facilitate direct communication between students and mentors.

**Benefits**:
- **Immediate Support**: Quick answers to student queries.
- **Community Building**: Encourages interaction between students and mentors.
- **Feedback Loop**: Mentors can gather insights from students.

**Implementation Steps**:
- **Chat Feature**:
  - Private messaging for personal queries.
  - Group chats for specific events or topics.
- **Notification Alerts**: Alerts mentors when they receive messages.
- **Chat Guidelines**: Provide guidelines for respectful communication.

### 3. Dashboard for Event Management

**Objective**: Create a centralized dashboard for admins.

**Benefits**:
- **Centralized Control**: View, edit, or delete events from one interface.
- **Analytics**: Insights on event attendance and engagement.
- **Task Management**: Assign tasks related to event planning.

**Implementation Steps**:
- **Event Overview Section**: Display upcoming and past events with status indicators.
- **Mentor Availability Schedule**: Calendar feature for mentors to indicate availability.
- **Feedback Collection Tool**: Feature to collect participant feedback post-event.

**Comment by wajeshubham** [comment]
This repository is not related to coding hero. This is a separate project independent of coding hero

**Comment by Code-With-Abhishek-Kumar** [comment]
> This repository is not related to coding hero. This is a separate project independent of coding hero

Yes but i try to Find Official coding hero repo Link but i don't got so if you have idea about this then plz give me repo link I Will rise my complain there
