### ISSUE TITLE
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension

### ISSUE THREAD

**Issue by Gagan2325** [hiteshchoudhary/apihub#26]
<a href="https://ibb.co/tQRbkP1"><img src="https://i.ibb.co/tQRbkP1/Screenshot-55.png" alt="Screenshot-55" border="0"></a>

**Comment by jwala-anirudh** [comment]
Hi @Gagan2325,
Please specify the issue related information in the following format to make it clear.
Thank you.

# Issue

## Description

## Severity

## Steps to reproduce

## Screenshots

## Comments

**Comment by wajeshubham** [comment]
@Gagan2325 You can open a fresh issue with the bug report template and kindly elaborate and provide some essential data related to the issue. 

Thank you!
