### ISSUE TITLE
BUG: Local seeding not working 

### ISSUE THREAD

**Issue by Builder-Byte** [hiteshchoudhary/apihub#262]
### Describe the bug

The swagger document provided for the local setup as  shown in [Hitesh's Youtube Video](https://www.youtube.com/watch?v=dtzfTePFKgM) no longer works. The api hits the " https://api.freeapi.app/" url instead of the localhost. Though hitting localhost from postman still gets the desired output.
![Screenshot from 2024-11-02 15-15-26](https://github.com/user-attachments/assets/c7b8b9f1-a617-4fec-9c95-665f89e84fb3)

**Comment by wajeshubham** [comment]
refer: https://github.com/hiteshchoudhary/apihub/issues/263
