### ISSUE TITLE
BUG :  Local Server Not Found in Server List

### ISSUE THREAD

**Issue by palasa-navadeep** [hiteshchoudhary/apihub#263]
The local server is not appearing in the list of available servers, which is causing requests to default to https://api.freeapi.app. However, when making requests directly from the local server using Postman, responses are received as expected.

![Screenshot 2024-11-02 163648](https://github.com/user-attachments/assets/0fc97c07-44cd-45a6-9881-7fa1ed057374)
![Screenshot 2024-11-02 163732](https://github.com/user-attachments/assets/a6fe2d14-5d91-41e6-b445-47020e67228c)

**Comment by wajeshubham** [comment]
https://github.com/hiteshchoudhary/apihub/blob/d0388a69e378e9eb5d1e5a4020fff2d65c0adf86/README.md?plain=1#L235 Instructions are given
