### ISSUE TITLE
BUG: The live demos at freeapi.app don't work now

### ISSUE THREAD

**Issue by jungleford** [hiteshchoudhary/apihub#268]
### Describe the bug

All demos in the official website cannot work properly.

### To Reproduce

1. Open the demo page: https://freeapi.hashnode.space/api-guide/apireference/getUsers
2. Click the "Run Code" button on the right side.
3. No result in the "Response" box.
4. And wait for a while, the server returns CORS error.

### Expected behavior

The server should return 200 OK and carry the correct data, as well as before.

### Screenshots

![Screenshot of Get users](https://github.com/user-attachments/assets/df6f7585-9150-4997-b4ce-0a6f4d4835ff)

### OS

Windows

### OS Version

10

### Client

Chrome

### Additional context or Information

Seems that some configurations failed on the server side.

**Comment by hritikmittal09** [comment]
it is cors error according to me something is wrong with .wnv file for server side

**Comment by Harsimran141** [comment]
i have also tried but api are not working

**Comment by BotShipper** [comment]
Oh no I am using API for my project

**Comment by Harsimran141** [comment]
Thanks for your support now its working
