### ISSUE TITLE
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json"

### ISSUE THREAD

**Issue by Gagan2325** [hiteshchoudhary/apihub#30]
What I did
Step 1: I cloned the project first.
Step 2:create .env file.
Step 3: Copy .env.sample file into .env.
Step 4: Run the yarn install command.
Step 5: Run the yarn start command.
When I ran the yarn command, I got an error.

<a href="https://ibb.co/tQRbkP1" target="_blank"><img src="https://i.ibb.co/tQRbkP1/Screenshot-55.png" alt="Screenshot-55" border="0"></a>

**Comment by wajeshubham** [comment]
@Gagan2325 Image is not clear kindly update the same.

**Comment by Gagan2325** [comment]
my node version is 16.14.0

![image](https://github.com/hiteshchoudhary/apihub/assets/112059240/524aea89-2eea-4c29-9699-91e3e449356b)

**Comment by jwala-anirudh** [comment]
Hi @Gagan2325, have you installed `yarn` on your machine?

**Comment by Gagan2325** [comment]
yes

**Comment by jwala-anirudh** [comment]
As per the screenshot, I can see it is giving a message `error Command "yarn" not found` can you please confirm

**Comment by Gagan2325** [comment]
I installed yarn 

![image](https://github.com/hiteshchoudhary/apihub/assets/112059240/574b79ea-9537-4ec0-bc38-8a053f6d6bc2)

**Comment by jwala-anirudh** [comment]
Understood, the project imports for `.json` files is supported for `v17.5.0` onwards. So I would the issue can be resolved by installing the latest LTS version of Node Js i.e. `v18.7.0`

Visit: https://nodejs.org/en

**Comment by wajeshubham** [comment]
@Gagan2325 From Node.js version 17.5.0 onward, importing a JSON file is possible using [Import Assertions](https://nodejs.org/api/esm.html#json-modules):

You are using node `v16.14.0` which does not have the support. We have raised a [PR](https://github.com/hiteshchoudhary/apihub/pull/31) for the issue. However, please update your version to current `LTS` node version to stay updated and it should fix the issue.

**Comment by Gagan2325** [comment]
thanks @jwala-anirudh @wajeshubham its works fine.
