### ISSUE TITLE
Refactor: need of a common validator for checking mongo ids in route path variables or inside the body

### ISSUE THREAD

**Issue by wajeshubham** [hiteshchoudhary/apihub#36]
# **Describe the issue**

Currently, the application utilizes separate validators for each endpoint that requires validation of MongoDB Ids passed within the route path variable (utlized more frequently) or request body (rarely used). 

This approach leads to code duplication violating the [DRY (Don't Repeat Yourself)](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle. The same validation logic is repeated multiple times for different endpoints, causing maintenance overhead and making the codebase less maintainable (may be).

# **Expected solution**

To address this issue and adhere to the DRY principle, it is recommended to create a common validator function that can handle the validation of MongoDB Ids by accepting the id name as a parameter. 

This common validator function can be reused across all endpoints where MongoDB Id validation is needed, reducing the redundant code.

# **Proposed common validator functions**

The proposed common validator function should accept an "idName" parameter, which represents the name of the MongoDB Id to be validated in the route path variable or request body. Here's a general outline of the proposed common validator function:

```js
import { body, param } from "express-validator";

/**
 *
 * @param {string} idName
 * @returns ValidationChain[]
 * @description A common validator responsible to validate mongodb ids passed in the url's path variable
 */
const mongoIdPathVariableValidator = (idName) => {
  return [
    param(idName).notEmpty().isMongoId().withMessage(`Invalid ${idName}`),
  ];
};

/**
 *
 * @param {string} idName
 * @returns ValidationChain[]
 * @description A common validator responsible to validate mongodb ids passed in the request body
 */
const mongoIdRequestBodyValidator = (idName) => {
  return [body(idName).notEmpty().isMongoId().withMessage(`Invalid ${idName}`)];
};
```

# **Folder structure to be followed**

Create a folder named `common` inside the `src/validators` folder. Add an `index.js` file and add proposed validators inside it.

# **How to use the common validator functions**

To validate MongoDB Ids for different endpoints, you can now simply call the `mongoIdPathVariableValidator` or `mongoIdRequestBodyValidator` functions with the corresponding `idName` as a parameter. Here's an example of how to use the common validator function for the three mentioned endpoints:

```js
// Following are the dummy endpoints just for a reference
import {
  mongoIdPathVariableValidator,
  mongoIdRequestBodyValidator
} from "../route.to.validators";
import { validate } from "../../../validators/validate.js"; // validation middleware

// http://localhost:8080/api/v1/users/:userId
router
  .route("/:userId")
  .get(
    mongoIdPathVariableValidator("userId"),
    validate,
    getUserById
  );

// http://localhost:8080/api/v1/orders/place-order
router
  .route("/place-order")
  .post(
    // to place order user needs to select an address from his/her profile. which client will pass in the request body
    mongoIdRequestBodyValidator("addressId"), 
    validate,
    placeOrder
  );
```

By using the `mongoIdPathVariableValidator` function, you eliminate the need for separate validator functions for each endpoint and promote code reuse, making the codebase more maintainable and efficient.

# **Additional context**

The proposed solution provides two common validator functions that significantly reduces code duplication and promotes the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle. 

By using this common function, you can easily validate MongoDB Ids for different endpoints without repeating the same validation logic. 

Additionally, if there are future changes or improvements to be made in the MongoDB Id validation process, you only need to modify the common validator function, and the changes will automatically apply to all endpoints that use it.

**Let's discuss before starting the implementation 🚀**

**Comment by sangameshsomawar** [comment]
@wajeshubham @hiteshchoudhary I would like to pick this up.

**Comment by wajeshubham** [comment]
Hey @sangameshsomawar,

Thank you for stepping up to take on the issue. Your willingness to tackle this challenge is greatly appreciated!

Before you begin, I want to encourage you to feel free to reach out and ask if you have any questions or doubts about the issue or the proposed solution or if you want any assistance regarding the same.

Once again, thank you for taking this on, and I'm looking forward to seeing your PR 🚀!

Best regards,
FreeAPI team

**Comment by Piyush-onGIT** [comment]
Hey, @wajeshubham @hiteshchoudhary I would like to work on this issue.

I was trying to analyze the codebase, and I have some doubts, are we talking about the validators that are defined inside the folder `src/validators/apps/<some-app-name>/<someValidator.validators.js>`?

**Comment by wajeshubham** [comment]
Hey @Piyush-onGIT

Thank you for expressing your interest in contributing to the issue 😀! We truly appreciate your enthusiasm and willingness to be a part of our development efforts.

Currently, another developer has already started working on the implementation for this specific issue. However, don't worry; there will be plenty of exciting opportunities 🚀in the future to contribute as we continue refactoring and enhancing the codebase.

We value your interest and would like to keep you in the loop regarding any new `good first issues` ☘️ that arise during our progress.

If you have any questions or need any assistance, feel free to reach out at any time.

Once again, thank you for your interest in contributing, and we'll be sure to keep you informed about upcoming opportunities!

Best regards,
FreeAPI team
