### ISSUE TITLE
[enhancement]: Migration to TypeScript

### ISSUE THREAD

**Issue by devsnb** [hiteshchoudhary/apihub#44]
## Background

Right now FreeApi.app is completely written is JavaScript. TypeScript has become an industry standard nowadays. Having the codebase migrated to TypeScript will benifit the developers to better understand the codebase.  TypeScript will benifit the project with better type-safety and tooling and thus it will result in improved code quality and confidence in code refactor.

## Plan

To incrementally migrate to TypeScript because of it's type-safety and tooling. We can have a discussion below for any better alternatives or reasons as to why not to migrate to TypeScript at all.

## Outcome

1. Improved code quality
2. Avoid unnecessary common bugs
3. Confidence to refactor the codebase
4. Better IDE/Text Editor Code completion
5. Better readability of the codebase

## Note

I'm not suggesting complete rewrite of the codebase but incremental adoption of TypeScript.
If possible kindly leave this issue open for discussion.

**Comment by sathishs007s** [comment]
shall i join in to changing to typescript

**Comment by devsnb** [comment]
@sathishs007s before starting to work on the issue let's wait for other contributors/maintainers for their comment on the matter. I think it's still too early to take on the job.

**Comment by AnkitKadam567** [comment]
Hi, I would like to participate in this task

**Comment by devsnb** [comment]
@hiteshchoudhary  yeah I understand what you mean. Thanks for the insight, will try to contribute to the project after I test it out a bit more.
