### ISSUE TITLE
BUG not able to hit get request for "my profile" in ecommerce app. Response is 401 not authorized, but parameters are not taking any user related input. 

### ISSUE THREAD

**Issue by praveenpugazh** [hiteshchoudhary/apihub#47]
## **Describe the bug**
BUG not able to hit get request for "my profile" in ecommerce app. Response is 401 not authorized, but parameters are not taking any user related input. 

## **To Reproduce**
go to swagger, ecommerce, get /ecommerce/profile -> returning not authorized as response

## **Desktop (please complete the following information):**

- Client [e.g. postman, thunder client, chrome, safari]

**Comment by wajeshubham** [comment]
@praveenpugazh It appears that you haven't yet registered or logged into an account. 

To access protected routes like `my-profile` within the Ecommerce app, you must first register and log in using the Authentication app's `register` and `login` APIs which will set a jwt token in the cookies.

This authentication app is a shared component utilized across various applications wherever user authorization and authentication are necessary in the FreeAPI project.

So, first create a user, log into the account and then try to access `my-profile`. If you have any doubts or questions, please don't hesitate to ask.
