### ISSUE TITLE
Adding chat issue, message in alert - "$lookup with 'pipeline' may not specify 'localField' or 'foreignField'"

### ISSUE THREAD

**Issue by WasyfAli** [hiteshchoudhary/apihub#48]
Adding chat issue, message in alert - "$lookup with 'pipeline' may not specify 'localField' or 'foreignField'"

**Comment by wajeshubham** [comment]
@WasyfAli kindly elaborate on the issue. Please provide detailed description, steps to reproduce and also share a screenshot of the alert and server terminal logs so that, we can understand the issue, it's location and it's cause.

Regards,
FreeAPI team

**Comment by wajeshubham** [comment]
Closing the issue due to inactivity. If you have further queries kindly reopen the issue. 

Thanks
