### ISSUE TITLE
 Add items in Cart

### ISSUE THREAD

**Issue by DKdev117** [hiteshchoudhary/apihub#54]
@wajeshubham adding items to the cart is not working. show the some Error I want to add any item 

=>Error:{
  "statusCode": 500,
  "data": null,
  "success": false,
  "errors": [],
  "message": "Cannot read properties of null (reading 'items')",
  "stack": "TypeError: Cannot read properties of null (reading 'items')\n    at 
               file:///E:/BackEnd/Node%20js/FreeApi_App/apihub/src/controllers/apps/ecommerce/cart.controllers.js:140:29\n    at 
                process.processTicksAndRejections (node: internal/process/task_queues:95:5)"
}

https://github.com/hiteshchoudhary/apihub/assets/131585729/9ece3432-f6e5-4b21-9b05-7f35d48f50e5

=> Watch the Video Better Understanding of How to Work Add item in cart

=>user add an item is only one it is not right because the user can multiple item cart

=>user add an item only one it is not right because the user can also add multiple items cart. it is some Problem that can be changed

**Comment by wajeshubham** [comment]
@DKdev117 Did you register the user before logging in?

**Comment by DKdev117** [comment]
> Did you register the user before logging in?

yes

**Comment by DKdev117** [comment]
first add item in cart  ok but remove the item from the database and again try add item to show this issue

**Comment by wajeshubham** [comment]
What do you mean by "remove item from the database?" Can you please elaborate

**Comment by DKdev117** [comment]
> What do you mean by "remove item from the database?" Can you please elaborate
when add to item in  cart first time add item in cart successfully. no Error but   the data is store in Mongodb database in cart schema when I am cart schema under add item cart data is deleted and try again to add item in cart to show this Error. did you understand please Reply yes

**Comment by wajeshubham** [comment]
@DKdev117 are you deleting the cart schema of the logged in user manually from the database? It would be great if you record the whole flow from register to the error including whatever you are doing in the database

**Comment by DKdev117** [comment]
> @DKdev117 are you deleting the cart schema of the logged in user manually from the database? It would be great if you record the whole flow from register to the error including whatever you are doing in the database

 
I am following this step

step 1: register
step 2: Login
step 3:Create category
step 4:create product
step 5:add item cart 


First time add item cart successfully. after clear All item in cart and page refresh and again try add item in cart same product I'd show this issue: can not read property undefined

**Comment by wajeshubham** [comment]
How are you clearing the cart? Using a `clear cart api` or are you deleting the cart schema from the database?

**Comment by DKdev117** [comment]
> How are you clearing the cart? Using a `clear cart api` or are you deleting the cart schema from the database?

I am cleaning the cart using deleting the cart schema from the database. after try to add item to  cart show this error

**Comment by wajeshubham** [comment]
@DKdev117 **You should never, ever delete anything from the DB manually unless you are 1000% sure of what you are doing. The error that you shared in the issue states that the cart for the logged-in user does not exist.**

If you delete the cart schema from the DB, this error makes sense because you are deleting the entire cart associated with the user from the DB _(which we never do)_. 

**Please don't perform manual operations on the DB;** instead, use APIs for such tasks. We have a `clear cart` API that you can use to empty the cart. This API does not delete the cart but rather makes the cart items array empty, which is the correct way to clear the cart.

Regards,
FreeAPI team

**Comment by DKdev117** [comment]
> @DKdev117 **You should never, ever delete anything from the DB manually unless you are 1000% sure of what you are doing. The error that you shared in the issue states that the cart for the logged-in user does not exist.**
> 
> If you delete the cart schema from the DB, this error makes sense because you are deleting the entire cart associated with the user from the DB _(which we never do)_. 
> 
> **Please don't perform manual operations on the DB;** instead, use APIs for such tasks. We have a `clear cart` API that you can use to empty the cart. This API does not delete the cart but rather makes the cart items array empty, which is the correct way to clear the cart.
> 
> Regards,
> FreeAPI team

I am clear cart api using delete item it will also show same issue 
 I am both way to remove the item in cart
