### ISSUE TITLE
how to work payment Gateway in paypal

### ISSUE THREAD

**Issue by DKdev117** [hiteshchoudhary/apihub#55]
Hi @wajeshubham , please explain how to work the payment Gateway with Paypal to me.

**Comment by wajeshubham** [comment]
@DKdev117, you need to create a PayPal account on Braintree and bring your PayPal client ID and PayPal secret to the .env file. It should work out of the box. However, we are planning a detailed YouTube tutorial for the payment gateways, which will include a comprehensive guide on how to set up a PayPal account and integrate it with a fully functional frontend. So, please stay tuned...
