### ISSUE TITLE
BUG  AuthContext values (token and user) are null in PrivateRoute component

### ISSUE THREAD

**Issue by azr-arch** [hiteshchoudhary/apihub#56]
**Description:**

Upon successful login, the user is correctly redirected to the `/chat` route. However, if the user manually changes the URL to `/login` and then attempts to navigate back to `/chat`, the `PrivateRoute` component prevents this navigation. This behavior occurs because the `token` and `user` values in `AuthContext` are `null` for an instance, causing the `PrivateRoute` component to redirect the user as if they were not authenticated.

**Steps to reproduce:**

1. Log in successfully, which redirects to the `/chat` route.
2. Manually change the URL to `/login`.
3. Attempt to navigate back to `/chat`.

**Expected behavior:**

The user should be able to navigate to `/chat` after step 3 since they are already authenticated.

**Actual behavior:**

The `PrivateRoute` component prevents navigation to `/chat` because it reads `token` and `user` as `null`.

**Additional context:**

**Comment by wajeshubham** [comment]
Hi @azr-arch,

Thank you for bringing up this concern. I appreciate your diligence in testing and reporting issues. 

I've attempted to replicate the problem you described, but it seems to be working as expected on my end. The `PrivateRoute` component correctly allows navigation to the `/chat` route after successful login, even if I manually change the URL to `/login` and then attempt to navigate back to `/chat`. 

To assist you better, could you please provide more details about your environment, such as the browser you are using and any specific steps you might have taken that could be affecting the behavior? 

Additionally, if the issue persists, it would be incredibly helpful if you could provide a screen recording or detailed steps to reproduce the problem. This will allow us to have a clearer understanding of the issue and help us address it more effectively.

Thank you for your cooperation, and we'll do our best to resolve any potential issues you might be experiencing.

Best regards,
FreeAPI team

**Comment by azr-arch** [comment]
@wajeshubham it appears that the problem might be specific to my machine. I apologize for any inconvenience this may have caused
