### ISSUE TITLE
Image which will be created from Dockerfile will be of large size.

### ISSUE THREAD

**Issue by aakash176** [hiteshchoudhary/apihub#61]
I can make some changes to the Dockerfile to make light weight image from it. Please assign this to me.

**Comment by aakash176** [comment]
@wajeshubham  When we use FROM node, this uses the official Node.js Docker image , which is based on a Debain-based image which tends to be larger because they include more comprehensive set of packages. and on the other hand if we use FROM node-alpine, this uses the Alpine Linux-based Node.js image. Using Alpine makes the resulting image significantly smaller compared to the Debain-based image.
Benefit of using Alpine based image are: occupies less memory, faster to build image, easy maintainability, security because it uses less depend libraries.

**Comment by wajeshubham** [comment]
Hi @aakash176 ,

While we understand the benefits of Alpine Linux, our current focus is on delivering more and more API services. 

Docker image optimization is a consideration, but we're afraid of potential impacts on compatibility. Regarding the use of Alpine Linux, we acknowledge that while it offers benefits such as reduced image size and faster build times, there are compatibility considerations, particularly with native dependencies and libraries. 

We are aware that Alpine uses the `musl` libc library, and **this can give challenges with certain npm packages and Node.js modules compiled against `glibc` which can cause serious problems in production as the FreeAPI project is versatile and we are adding more and more modules in future. So, its a diverse project.**

Your feedback is valuable, and we're open to future enhancements. Feel free to share any specific recommendations.

Thanks again for your contribution.

Best,
FreeAPI team
