### ISSUE TITLE
feat: social media app web frontend

### ISSUE THREAD

**Issue by Rudra-Patel-code** [hiteshchoudhary/apihub#71]
# Social Media Web App

## Overview

To develop a social media web application using React.js ( with typescript ), Shadcn, Tailwind CSS, and React Redux. 

## Technologies to be Used

- **React.js**: A JavaScript library for building user interfaces.
- **Shadcn**: A collection of open-source UI components and tools for building web applications.
- **Tailwind CSS**: A utility-first CSS framework for rapidly building custom designs.
- **React Redux**: A state management library for React applications.

## Features

- **User Authentication**: Implement a secure user authentication system to allow users to create accounts and log in.
- **Profile Pages**: Enable users to customize their profiles, add profile pictures, and update personal information.
- **Post Creation and Interaction**: Implement the ability for users to create posts, comment on posts, and like posts.
- **Responsive Design**: Ensure the web app is responsive and accessible across various devices.

**Comment by wajeshubham** [comment]
Hi @Rudra-Patel-code ,

Thank you for expressing your interest in developing the Social Media Web App for our FreeAPI project.

To ensure smooth collaboration and consistency across contributions, we kindly request that you follow our recommended project structure for frontend applications.

Here's the suggested folder structure for your Social Media Web App:

```bash
$ROOT_FOLDER/examples/apps/social-media/web/react-shadcn-tailwind-redux/<project_code>
# <project_code> will be the project files of your project.
```

Please, raise a PR, we will assign you this task and we will keep it in draft unless the review is over.

If you have any questions or need further clarification, please don't hesitate to reach out. We're looking forward to seeing your innovative contributions!

Best regards,
FreeAPI Team

**Comment by Rudra-Patel-code** [comment]
@wajeshubham 

Here the design of some screens , for the app. These are just the idea of the screen and the ui of actual app will be very close to this as possible.

https://www.figma.com/file/VVj9s1XjUMLwoUA6O27dI6/social-media?type=design&node-id=0%3A1&mode=design&t=rfu4wUNrIjrUv1ZR-1

I need an approval for this design

**Comment by wajeshubham** [comment]
@Rudra-Patel-code looks great! We already have all the social media application UI pages covered on DevUI. You can find all the pages and components of social media app with their html-tailwind code [here](https://devuiv2.vercel.app/templates/social-media). This will save you a ton of time 😀

**Comment by Rudra-Patel-code** [comment]
@wajeshubham 

I looked at the designs from [devui](https://devuiv2.vercel.app/templates/social-media) . But I thought I should also explore my designing side so I designed my own UI. It will enhace my confidence If I can create good designs on my own.

**Comment by jeevankc17** [comment]
@wajeshubham can I get these figma files of devui. I am looking to contribute.

**Comment by wajeshubham** [comment]
@Rudra-Patel-code any update on the status of the application?
