### ISSUE TITLE
FEATURE: Logging Enhancement Proposal

### ISSUE THREAD

**Issue by wajeshubham** [hiteshchoudhary/apihub#74]
### Describe the Feature

I propose the implementation of comprehensive logging for the FreeAPI backend project. The logging should cover both normal application-level logs and detailed API call logs. (Application level logs can be centralized by injecting logger into the error middleware as that is the central place where the errors are being handled)

**IMPORTANT:**

Our emphasis is not on complex logging by logging each line in the application but rather on strategic logging:

- HTTP API Call Logs: To be implemented using something like Morgan middleware in the `app.js`
- Application-Level **Error** Logs: To be implemented in the error middleware of FreeAPI, the central place for handling errors with informative messages.

### Use Case

This enhancement aims to improve the overall observability and debugging capabilities of the FreeAPI backend. With centralized logging, we can efficiently track application activities, monitor errors, and gain insights into API interactions.

### Additional Information

Implementing a centralized Morgan middleware for HTTP API calls and integrating Winston for application-level logs can greatly enhance our ability to track, analyze, and troubleshoot issues efficiently.

### Suggested Tools

**Winston (for application-level logs):**

- A versatile and customizable logging library for Node.js.
- Offers support for multiple transports (console, file, etc.).
- Allows log level configuration for different environments.

**Morgan (for API call logging):**

- Middleware for Express.js to log HTTP requests and responses.
- Can be customized to log specific details, such as status codes, request methods, and response times.
- Helps in centralizing API call logs for better analysis and monitoring.

### Priority:
Medium

### Effort Estimate:
Approximately 2-3 days for implementation and integration.

### Purpose:
Centralized logging will streamline error handling and provide valuable insights into the FreeAPI backend's behavior. This enhancement aligns with the project's goal of maintaining a robust and easily maintainable codebase.

### Contributions are welcome
If you're interested in contributing to the implementation of this feature, feel free to let us know!

**Comment by joyMajumder123** [comment]
want to give it a try

**Comment by wajeshubham** [comment]
Hey @joyMajumder123 ,

Thank you for expressing your interest in implementing the logging feature for the FreeAPI backend project.

If you have any questions or doubts about the feature's requirements or implementation details, please don't hesitate to reach out. We're here to provide clarification and support at every step of the way.

However, if you're confident and ready to take on the challenge, we encourage you to proceed with the implementation.

Remember, we're here to assist you in any way needed. Feel free to reach out for further discussion or guidance. Please raise a PR from the forked repository's branch.

Best regards,
FreeAPI team

**Comment by tarun-kavipurapu** [comment]
Hey @wajeshubham I just created a pull request implementing the features that you just mentioned 

Since further information about format or output method was not mentioned i displayed the error and http logs on Console

I am Happy to make any further changes to the loggers that you suggest

Hope you are satisfied by the contribution

**Comment by wajeshubham** [comment]
@tarun-kavipurapu Please address the reviewed changes. 

_Originally posted by @wajeshubham in https://github.com/hiteshchoudhary/apihub/pull/80#pullrequestreview-1868457146_

**Comment by tarun-kavipurapu** [comment]
Hey, @wajeshubham  implemented all the changes that you mentioned in #80

**Comment by wajeshubham** [comment]
Implemented in PR: #80 Thanks @tarun-kavipurapu & @joyMajumder123 for the participation
