### ISSUE TITLE
FEATURE: Add more youtube backend api

### ISSUE THREAD

**Issue by DKdev117** [hiteshchoudhary/apihub#84]
###  **features list of you tube video application** 

- upload video
- delete video
- update video file
- watch video
- get user liked videos
- add comment on videos
- get all comment on videos
- get liked videos
- get subscribed channels 
- add small tweet section
- toggle like on video
- toggle subscribed on video channel 
- likes on video comment
- create video Playlist
- removed playlist videos
- update video playlist
- get channel statictis information

### help to beginners

**help to lot of people they not able pay youtube video api and they want to  create a video app**

### Additional Information

@hiteshchoudhary 
**hello everyone**

I want to contribute video API features. 
plese assign video api task me

### technologies

1. Node js
2. Express js
3. Mongodb
4. Api Testing [Postman]
5. Api formating [Swgger]

**Comment by DKdev117** [comment]
thank you @wajeshubham

**Comment by wajeshubham** [comment]
Any update on this @DKdev117 ?

**Comment by arnb-smnta** [comment]
@DKdev117 Would like to help you out with the api's I am also a contributor like you would like to help you out if you will let me in your repo i will fork it and help make the rest api's it will be faster and i will be able to learn more out of it as there are many api you are building would like to help

**Comment by wajeshubham** [comment]
Closing due to closed PR: https://github.com/hiteshchoudhary/apihub/pull/128 Let's keep further communication on closed PR. The requested changes are still not reflected in the PR kindly check. Thank you!
