### ISSUE TITLE
Not load images in / public / randomproducts !!

### ISSUE THREAD

**Issue by itsmashal** [hiteshchoudhary/apihub#93]
i use / public / randomproducts API in my project and when i want to access the images from this api data it will show "Cross-Origin Read Blocking (CORB) blocked a cross-origin response" this message in console section. can you tell my what's the problem.
![productErr](https://github.com/hiteshchoudhary/apihub/assets/138968185/bfdcdaae-49fc-4b59-a27f-bfd641254ff3)

**Comment by wajeshubham** [comment]
@itsmashal Thanks for pointing out the issue. Working on it!

**Comment by pankajkhuswaha** [comment]
this images is not working because dummyjson change images urls can i fix this
