### ISSUE TITLE
Mongo db connection error in chat app

### ISSUE THREAD

**Issue by rashap224** [hiteshchoudhary/apihub#97]
MongoDB connection error:  MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://www.mongodb.com/docs/atlas/security-whitelist/
    at _handleConnectionErrors (F:\apihub-main\apihub-main\node_modules\mongoose\lib\connection.js:788:11)  
    at NativeConnection.openUri (F:\apihub-main\apihub-main\node_modules\mongoose\lib\connection.js:763:11) 
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async connectDB (file:///F:/apihub-main/apihub-main/src/db/index.js:9:32) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(3) {
      'ac-nodlse8-shard-00-00.iaka6gp.mongodb.net:27017' => [ServerDescription],
      'ac-nodlse8-shard-00-02.iaka6gp.mongodb.net:27017' => [ServerDescription],
      'ac-nodlse8-shard-00-01.iaka6gp.mongodb.net:27017' => [ServerDescription]
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'atlas-ppkt0r-shard-0',
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined
}
[nodemon] app crashed - waiting for file changes before starting...
  I am getting this error again and again despite checking my ip address and cluster in network access section. I got this several times what to do??? I have tried every possible way to solve this but no results??

**Comment by wajeshubham** [comment]
@rashap224 Make sure you have allowed all IPs to access the mongo cluster i.e. `0.0.0.0/0` (not recommended for production), don't put your public IP as it might be dynamic and changing time to time. Also, if you are behind a firewall or VPN this issue might occur, try connecting to a cellular network, then connect through a mobile hotspot and see if it works.

**Comment by rashap224** [comment]
I make sure that in network access section, I added my current IP address
and status is active with the cluster. I then moved to database section
where I clicked on connect -> compass -> connection uri. Then copy paste in
.env file with my correct username and password, remove the trailing slash
at the end. SAVED it and then again npm run start, but still the same error
that IP is not whitelisted.
I m literally frustrated because this happened with me with my previous
project also that mongodb is not connectedto server of my project.
I am using my wifi for it.
Please help me out. And also suggest me how to resolve this issue.

**Comment by wajeshubham** [comment]
Try adding `0.0.0.0/0` in whitelisted IP and remove your IP from it and check if that works. Also, share your mongo cluster URL that you are keeping in .env file.

**Comment by shrey-dadhaniya** [comment]
@rashap224 
please make sure that you can connect to your cluster using Mongo compass

**Comment by rashap224** [comment]
![IP address mongodb](https://github.com/hiteshchoudhary/apihub/assets/143923646/063ecc85-1fe3-4859-99fc-f211bd5b0122)
I deleted that project and started fresh on mongodb but same issue persists. 
My .env contains
 MONGODB_URI=mongodb+srv://rashap:8fDRMFZkL0EeXb8M@cluster0.1xfwvsk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0 # `mongodb://localhost:27017` in case using local mongodb

**Comment by rashap224** [comment]
> @rashap224 please make sure that you can connect to your cluster using Mongo compass

I connected using driver option, not compass because compass is not installed yet

**Comment by wajeshubham** [comment]
@rashap224 This is a firewall issue. I tried connecting the DB and I am able to establish a connection. Check your network and try with mobile hotspot. Also, please don't include your credentials here, change them on the atlas.

**Comment by rashap224** [comment]
so u mean my uri is correct but firewall issue is there. But my wifi is working fine, ok I ll try to connect with mobile hotspot also

**Comment by rashap224** [comment]
@wajeshubham I changed the password and updated it. I again paste the connection string with mew password but still same issue. 
Also, I connect using drivers not compass or other options. So does it affect the uri?? 
Also, from ur side, U r sure that my approach is correct for setting up mongodb, but firewall issue is there. 
I will try again and again.
Also, Do u have anything else like guidance or advice to tell me regarding this mongodb connection, because I really want to do my project.
Thanks!!

**Comment by rashap224** [comment]
@wajeshubham Issue solved. I connected today with same connection string with same credentials with mobile hotspot.
