### ISSUE TITLE
Complex chat app error- vite is not an internal and external command

### ISSUE THREAD

**Issue by rashap224** [hiteshchoudhary/apihub#98]
F:\apihub-main\apihub-main\examples\apps\chat-app\web\react-vite-tailwind>npm run dev

> vite-chat-app@0.0.0 dev
> vite

'vite' is not recognized as an internal or external command,
operable program or batch file.  While following the steps to learn socket.io from freeapi project taught by hitesh sir in english youtube channel, I m getting this thing again and again.  Do I need to install the vite again separately? Kindly help anyone.

**Comment by wajeshubham** [comment]
Please run `npm install` before starting the server. Please read `README.md` for more details.
